/**
 * compile-data.ts
 *
 * Reads raw monthly data files and writes engine-optimised compiled files.
 * Run after updating any raw data file:
 *   bun scripts/compile-data.ts
 *
 * Output files (committed to repo):
 *   src/data/compiled/returns/sp500.ts    — compound annual returns per start-month
 *   src/data/compiled/returns/tbond.ts
 *   src/data/compiled/returns/gold.ts
 *   src/data/compiled/inflation/us.ts     — YoY inflation Maps (direct copy, Map format)
 *   src/data/compiled/inflation/singapore.ts
 *   src/data/compiled/sp500Index.ts       — cumulative price index + running ATH
 */

import { sp500 }             from '../src/data/raw/returns/sp500';
import { tbond }             from '../src/data/raw/returns/tbond';
import { gold }              from '../src/data/raw/returns/gold';
import { usInflation }       from '../src/data/raw/inflation/us';
import { singaporeInflation } from '../src/data/raw/inflation/singapore';
import type { MonthlyDataPoint } from '../src/data/types';
import { writeFileSync } from 'fs';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function ymKey(year: number, month: number): number {
  return year * 100 + month;
}

function ymToLM(year: number, month: number): number {
  return year * 12 + (month - 1);
}

function lmToYM(lm: number): { year: number; month: number } {
  return { year: Math.floor(lm / 12), month: (lm % 12) + 1 };
}

/** Sort by linear month index */
function sortedByLM(values: MonthlyDataPoint[]): MonthlyDataPoint[] {
  return [...values].sort((a, b) => ymToLM(a.year, a.month) - ymToLM(b.year, b.month));
}

// ---------------------------------------------------------------------------
// Compound annual returns: for each valid start month, compound 12 consecutive
// monthly returns into a single annual return value.
// ---------------------------------------------------------------------------

function compileAnnualReturns(values: MonthlyDataPoint[]): Map<number, number> {
  const sorted = sortedByLM(values);
  // Build a quick Map<lm, value> for O(1) lookup
  const byLM = new Map<number, number>(
    sorted.map(d => [ymToLM(d.year, d.month), d.value])
  );

  const minLM = ymToLM(sorted[0].year, sorted[0].month);
  const maxLM = ymToLM(sorted[sorted.length - 1].year, sorted[sorted.length - 1].month);

  const result = new Map<number, number>();

  // A 12-month window starting at lm needs data through lm+11
  for (let startLM = minLM; startLM <= maxLM - 11; startLM++) {
    let compound = 1;
    let valid = true;
    for (let k = 0; k < 12; k++) {
      const v = byLM.get(startLM + k);
      if (v === undefined) { valid = false; break; }
      compound *= 1 + v;
    }
    if (valid) {
      const { year, month } = lmToYM(startLM);
      result.set(ymKey(year, month), compound - 1);
    }
  }

  return result;
}

// ---------------------------------------------------------------------------
// Inflation: direct YYYYMM → YoY rate Map
// ---------------------------------------------------------------------------

function compileInflation(values: MonthlyDataPoint[]): Map<number, number> {
  return new Map(values.map(d => [ymKey(d.year, d.month), d.value]));
}

// ---------------------------------------------------------------------------
// S&P 500 price index and running ATH
// ---------------------------------------------------------------------------

function compilesp500Index(values: MonthlyDataPoint[]): {
  priceIndex: Map<number, number>;
  runningATH: Map<number, number>;
} {
  const sorted = sortedByLM(values);
  const priceIndex = new Map<number, number>();
  const runningATH = new Map<number, number>();

  let price = 1.0;
  let ath = 0;
  for (const { year, month, value } of sorted) {
    price *= 1 + value;
    ath = Math.max(ath, price);
    const key = ymKey(year, month);
    priceIndex.set(key, price);
    runningATH.set(key, ath);
  }
  return { priceIndex, runningATH };
}

// ---------------------------------------------------------------------------
// File writer: emits a TypeScript file with a static Map literal
// ---------------------------------------------------------------------------

function mapToLiteral(m: Map<number, number>): string {
  const entries = [...m.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([k, v]) => `  [${k}, ${v}]`)
    .join(',\n');
  return entries;
}

function writeReturnFile(path: string, exportName: string, m: Map<number, number>, comment: string) {
  const content = `// Auto-generated by scripts/compile-data.ts — do not edit manually.
// ${comment}
export const ${exportName} = new Map<number, number>([
${mapToLiteral(m)}
]);
`;
  writeFileSync(path, content, 'utf8');
  console.log(`  Written: ${path} (${m.size} entries)`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

console.log('Compiling data files...');

// Returns
const sp500Annual  = compileAnnualReturns(sp500.values);
const tbondAnnual  = compileAnnualReturns(tbond.values);
const goldAnnual   = compileAnnualReturns(gold.values);

writeReturnFile(
  'src/data/compiled/returns/sp500.ts',
  'sp500AnnualReturns',
  sp500Annual,
  'Each key is YYYYMM; value is compound annual return for the 12-month window starting that month.',
);
writeReturnFile(
  'src/data/compiled/returns/tbond.ts',
  'tbondAnnualReturns',
  tbondAnnual,
  'Each key is YYYYMM; value is compound annual return for the 12-month window starting that month.',
);
writeReturnFile(
  'src/data/compiled/returns/gold.ts',
  'goldAnnualReturns',
  goldAnnual,
  'Each key is YYYYMM; value is compound annual return for the 12-month window starting that month.',
);

// Inflation
const usInflMap  = compileInflation(usInflation.values);
const sgInflMap  = compileInflation(singaporeInflation.values);

writeReturnFile(
  'src/data/compiled/inflation/us.ts',
  'usInflationMap',
  usInflMap,
  'Each key is YYYYMM; value is the YoY CPI rate for that month.',
);
writeReturnFile(
  'src/data/compiled/inflation/singapore.ts',
  'singaporeInflationMap',
  sgInflMap,
  'Each key is YYYYMM; value is the YoY CPI rate for that month.',
);

// S&P 500 price index + ATH
const { priceIndex, runningATH } = compilesp500Index(sp500.values);

const indexContent = `// Auto-generated by scripts/compile-data.ts — do not edit manually.
// Keys are YYYYMM. Values are cumulative price index (base 1.0 before first data month).
export const sp500PriceIndex = new Map<number, number>([
${mapToLiteral(priceIndex)}
]);
// Running all-time high through each month (YYYYMM → max price seen up to and including that month).
export const sp500RunningATH = new Map<number, number>([
${mapToLiteral(runningATH)}
]);
`;
writeFileSync('src/data/compiled/sp500Index.ts', indexContent, 'utf8');
console.log(`  Written: src/data/compiled/sp500Index.ts (${priceIndex.size} entries each)`);

console.log('Done.');
